// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsvLxQYGkGgDu39I_oSb4s0jTFdeaU_y0',
    appId: '1:1020463082190:web:a81cbd6e27d469ef027e9f',
    messagingSenderId: '1020463082190',
    projectId: 'fittrack-a13dc',
    authDomain: 'fittrack-a13dc.firebaseapp.com',
    storageBucket: 'fittrack-a13dc.firebasestorage.app',
    measurementId: 'G-RSH19MTY0W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYlYIRSVRSpHmHh0kJuSpUT8_hkQx0khc',
    appId: '1:1020463082190:android:35f7fe5e5bd6b9aa027e9f',
    messagingSenderId: '1020463082190',
    projectId: 'fittrack-a13dc',
    storageBucket: 'fittrack-a13dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBadZ7320WfwJp99ryFcB81m8gjRyiEGeM',
    appId: '1:1020463082190:ios:7b55440ff4e98085027e9f',
    messagingSenderId: '1020463082190',
    projectId: 'fittrack-a13dc',
    storageBucket: 'fittrack-a13dc.firebasestorage.app',
    iosBundleId: 'com.example.fitTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBadZ7320WfwJp99ryFcB81m8gjRyiEGeM',
    appId: '1:1020463082190:ios:7b55440ff4e98085027e9f',
    messagingSenderId: '1020463082190',
    projectId: 'fittrack-a13dc',
    storageBucket: 'fittrack-a13dc.firebasestorage.app',
    iosBundleId: 'com.example.fitTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsvLxQYGkGgDu39I_oSb4s0jTFdeaU_y0',
    appId: '1:1020463082190:web:6e46a889f9ffc448027e9f',
    messagingSenderId: '1020463082190',
    projectId: 'fittrack-a13dc',
    authDomain: 'fittrack-a13dc.firebaseapp.com',
    storageBucket: 'fittrack-a13dc.firebasestorage.app',
    measurementId: 'G-58TPN05R78',
  );
}
