// ignore_for_file: sized_box_for_whitespace, use_key_in_widget_constructors, deprecated_member_use
import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          StatusBar(),
        ]),
      ),
    );
  }
}

class StatusBar extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 375,
          height: 44,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(),
          child: Stack(
            children: [
              Positioned(
                left: 21,
                top: 12,
                child: Container(
                  width: 54,
                  height: 21,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(32),
                    ),
                  ),
                  child: Stack(),
                ),
              ),
            ],
          ),
        ),
        Container(
          width: 375,
          height: 764,
          decoration: BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://placehold.co/375x764"),
              fit: BoxFit.fill,
            ),
          ),
        ),
        Container(
          width: 375,
          padding: const EdgeInsets.only(top: 16),
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: Colors.white.withValues(alpha: 0.80),
            shape: RoundedRectangleBorder(
              side: BorderSide(
                width: 1,
                strokeAlign: BorderSide.strokeAlignCenter,
                color: const Color(0xFFE5DFDA) /* Stroke */,
              ),
            ),
          ),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            mainAxisAlignment: MainAxisAlignment.start,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Container(
                width: double.infinity,
                padding: const EdgeInsets.symmetric(horizontal: 16),
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  spacing: 26,
                  children: [
                    Container(
                      width: 57,
                      child: Column(
                        mainAxisSize: MainAxisSize.min,
                        mainAxisAlignment: MainAxisAlignment.center,
                        crossAxisAlignment: CrossAxisAlignment.center,
                        spacing: 2,
                        children: [
                          Container(
                            width: 20,
                            height: 20,
                            clipBehavior: Clip.antiAlias,
                            decoration: BoxDecoration(),
                            child: Stack(
                              children: [
                                Positioned(
                                  left: 8.33,
                                  top: 9.17,
                                  child: Container(
                                    width: 3.33,
                                    height: 3.33,
                                    decoration: ShapeDecoration(
                                      color: Colors.white,
                                      shape: OvalBorder(),
                                    ),
                                  ),
                                ),
                              ],
                            ),
                          ),
                          Container(
                            width: double.infinity,
                            child: Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.center,
                              spacing: 6,
                              children: [
                                SizedBox(
                                  width: 57,
                                  child: Text(
                                    'Home',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: const Color(0xFF202226),
                                      fontSize: 11,
                                      fontFamily: 'Figtree',
                                      fontWeight: FontWeight.w400,
                                      height: 1.36,
                                      letterSpacing: -0.20,
                                    ),
                                  ),
                                ),
                                Container(
                                  width: 4,
                                  height: 4,
                                  decoration: ShapeDecoration(
                                    color: const Color(0xFF24211E) /* Colors-Neutral-1000 */,
                                    shape: OvalBorder(),
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ],
                      ),
                    ),
                    Container(
                      width: 57,
                      child: Column(
                        mainAxisSize: MainAxisSize.min,
                        mainAxisAlignment: MainAxisAlignment.center,
                        crossAxisAlignment: CrossAxisAlignment.center,
                        spacing: 2,
                        children: [
                          Container(
                            width: 20,
                            height: 20,
                            clipBehavior: Clip.antiAlias,
                            decoration: BoxDecoration(),
                            child: Stack(),
                          ),
                          Text(
                            'Workouts',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: const Color(0xFF8D8985) /* Colors-Neutral-500 */,
                              fontSize: 11,
                              fontFamily: 'Figtree',
                              fontWeight: FontWeight.w400,
                              height: 1.36,
                              letterSpacing: -0.20,
                            ),
                          ),
                        ],
                      ),
                    ),
                    Container(
                      width: 57,
                      child: Column(
                        mainAxisSize: MainAxisSize.min,
                        mainAxisAlignment: MainAxisAlignment.center,
                        crossAxisAlignment: CrossAxisAlignment.center,
                        spacing: 2,
                        children: [
                          Container(
                            width: 20,
                            height: 20,
                            clipBehavior: Clip.antiAlias,
                            decoration: BoxDecoration(),
                            child: Stack(
                              children: [
                                Positioned(
                                  left: 6.67,
                                  top: 6.67,
                                  child: Container(
                                    width: 6.67,
                                    height: 6.67,
                                    decoration: ShapeDecoration(
                                      shape: OvalBorder(
                                        side: BorderSide(
                                          width: 1,
                                          color: const Color(0xFF8D8985) /* Colors-Neutral-500 */,
                                        ),
                                      ),
                                    ),
                                  ),
                                ),
                              ],
                            ),
                          ),
                          SizedBox(
                            width: 57,
                            child: Text(
                              'Start',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                color: const Color(0xFF8D8985) /* Colors-Neutral-500 */,
                                fontSize: 11,
                                fontFamily: 'Figtree',
                                fontWeight: FontWeight.w400,
                                height: 1.36,
                                letterSpacing: -0.20,
                              ),
                            ),
                          ),
                        ],
                      ),
                    ),
                    Container(
                      width: 57,
                      child: Column(
                        mainAxisSize: MainAxisSize.min,
                        mainAxisAlignment: MainAxisAlignment.center,
                        crossAxisAlignment: CrossAxisAlignment.center,
                        spacing: 2,
                        children: [
                          Container(
                            width: 20,
                            height: 20,
                            clipBehavior: Clip.antiAlias,
                            decoration: BoxDecoration(),
                            child: Stack(),
                          ),
                          Text(
                            'Overview',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: const Color(0xFF8D8985) /* Colors-Neutral-500 */,
                              fontSize: 11,
                              fontFamily: 'Figtree',
                              fontWeight: FontWeight.w400,
                              height: 1.36,
                              letterSpacing: -0.20,
                            ),
                          ),
                        ],
                      ),
                    ),
                  ],
                ),
              ),
              Container(
                width: 402,
                height: 34,
                child: Stack(
                  children: [
                    Positioned(
                      left: 273,
                      top: 26,
                      child: Container(
                        transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(3.14),
                        width: 144,
                        height: 5,
                        decoration: ShapeDecoration(
                          color: Colors.black /* Black */,
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(100),
                          ),
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
        Container(
          width: 49,
          height: 49,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(),
        ),
      ],
    );
  }
}